# Generated by Django 5.0.6 on 2024-07-15 12:02

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(primary_key=True, serialize=False, validators=[main.models.validate_phone]),
        ),
    ]
