# Generated by Django 5.0.6 on 2024-07-15 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='user_phone',
            field=models.ForeignKey(db_column='user_phone', on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
